/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconArrowRight: typeof import('./src/components/icon/IconArrowRight.vue')['default']
    IconCommunity: typeof import('./src/components/icon/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icon/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icon/IconEcosystem.vue')['default']
    IconsIconArrowRight: typeof import('./src/components/icons/IconArrowRight.vue')['default']
    IconsIconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconsIconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconsIconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconsIconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconsIconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IconSupport: typeof import('./src/components/icon/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icon/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheNavigation: typeof import('./src/components/TheNavigation.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
