/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/base/BaseButton.vue')['default']
    BaseInput: typeof import('./src/components/base/BaseInput.vue')['default']
    BaseModal: typeof import('./src/components/base/BaseModal.vue')['default']
    BaseTable: typeof import('./src/components/base/BaseTable.vue')['default']
    copy: typeof import('./src/components/settings/SettingsAddPriceModal copy.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconArrowRight: typeof import('./src/components/icon/IconArrowRight.vue')['default']
    IconClose: typeof import('./src/components/icon/IconClose.vue')['default']
    IconCommunity: typeof import('./src/components/icon/IconCommunity.vue')['default']
    IconDashboard: typeof import('./src/components/icon/IconDashboard.vue')['default']
    IconDocumentation: typeof import('./src/components/icon/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icon/IconEcosystem.vue')['default']
    IconLoading: typeof import('./src/components/icon/IconLoading.vue')['default']
    IconSettings: typeof import('./src/components/icon/IconSettings.vue')['default']
    IconSupport: typeof import('./src/components/icon/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icon/IconTooling.vue')['default']
    IconTransactions: typeof import('./src/components/icon/IconTransactions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsAddPriceModal: typeof import('./src/c./src/components/settings/SettingsUpdatePriceModal.vue]
    SettingsUpdatePriceModal: typeof import('./src/components/settings/SettingsUpdatePriceModal.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheNavigation: typeof import('./src/components/TheNavigation.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
